### ISSUE TITLE
no sensors available

### ISSUE THREAD

**Issue by ibasaw** [bergware/dynamix#16]
just work the first time and now nothing

unraid 6.5.0
plugins : 2018.03.18

here the available driver
`coretemp nct7904`

but my select are all empty

`Model: Custom
M/B: Supermicro - X9DR3-F
CPU: Intel® Xeon® CPU E5-2690 v2 @ 3.00GHz
HVM: Enabled
IOMMU: Enabled
Cache: 640 kB, 2560 kB, 25600 kB
Memory: 64 GB Multi-bit ECC (max. installable capacity 192 GB)
Network: bond0: fault-tolerance (active-backup), mtu 1500 
 eth0: 100 Mb/s, full duplex, mtu 1500 
 eth1: 1000 Mb/s, full duplex, mtu 1500
Kernel: Linux 4.14.26-unRAID x86_64
OpenSSL: 1.0.2n
Uptime: `

in console when i launch the command :
`sensors
Error: File /etc/sensors.d/sensors.conf, line 2: Undeclared bus id referenced
Error: File /etc/sensors.d/sensors.conf, line 4: Undeclared bus id referenced
Error: File /etc/sensors.d/sensors.conf, line 6: Undeclared bus id referenced
Error: File /etc/sensors.d/sensors.conf, line 8: Undeclared bus id referenced
Error: File /etc/sensors.d/sensors.conf, line 10: Undeclared bus id referenced
Error: File /etc/sensors.d/sensors.conf, line 14: Undeclared bus id referenced
sensors_init: Can't parse bus name`

**Comment by ibasaw** [comment]
i had deleted the file /etc/sensors.d/sensors.conf and ow i can use sensors and it works in ssh

**Comment by ibasaw** [comment]
if i return to the plugins, i had the select with sensors temp; i click save and the problem come again; the plugins don't work on my server.

**Comment by Guruleenyc** [comment]
> i had deleted the file /etc/sensors.d/sensors.conf and ow i can use sensors and it works in ssh

This worked for me on my HP Z800, but I only get coretemp for each of my CPU cores :-/
Anyone know how to get my motherboard and GTX GPU sensors also?
