### ISSUE TITLE
Version 2023.02.04a does not show plugin page settings.

### ISSUE THREAD

**Issue by mihaiolimpiu** [bergware/dynamix#66]
Version 2023.02.04a does not show plugin page settings.

SYSTEM TEMP

Warning: require_once(/usr/local/emhttp/plugins/dynamix.system.temp/include/Legacy.php): failed to open stream: No such file or directory in /usr/local/emhttp/plugins/dynamix/include/DefaultPageLayout.php(693) : eval()'d code on line 16

Fatal error: require_once(): Failed opening required '/usr/local/emhttp/plugins/dynamix.system.temp/include/Legacy.php' (include_path='.:/usr/local/emhttp') in /usr/local/emhttp/plugins/dynamix/include/DefaultPageLayout.php(693) : eval()'d code on line 16

Temperature readings worked until first reboot.

**Comment by mihaiolimpiu** [comment]
Removed, reinstalled, issue persists.

**Comment by bergware** [comment]
Thanks for reporting.
I made an update to fix it.

**Comment by mihaiolimpiu** [comment]
2023.02.04b fixed it.
