### ISSUE TITLE
 autofan version 1.7 Parse error

### ISSUE THREAD

**Issue by SiggiBS** [bergware/dynamix#67]
After updating to autofan version 1.7 I get a parse error for pwm nct6796 when detecting the pwm fan:

<br /><b>Parse error</b>:  syntax error, unexpected ';', expecting ')' in <b>/usr/local/emhttp/plugins/dynamix.system.autofan/include/SystemFan.php</b> on line <b>65</b><br />

The preveous version worked well.

**Comment by bergware** [comment]
There was a typo. Made a correction.
Thanks for reporting.
