### ISSUE TITLE
Feature Request "File Manager" - Minimize windows

### ISSUE THREAD

**Issue by Joly0** [bergware/dynamix#68]
I dont know if this is possible, but it would be usefull to minimzize windows such as the move or copy window. 
This would be useful, because if one had to copy/move larger folders/files and therefore the window is in front for a prolonged period of time, its impossible to do anything in the webui in the meantime

**Comment by bergware** [comment]
You can close the window (click on the X in the top-right corner) and the process continues in the background.
When you open the File Manager again it will show the running process again.
