### ISSUE TITLE
s3_sleep script doesn't shutdown

### ISSUE THREAD

**Issue by rgls** [bergware/dynamix#7]
While putting unRAID to an S3 sleep with the script works perfectly, the shutdown option doesn't work.
The powerdown script is never called due to problems with the search path.
(See https://lime-technology.com/forum/index.php?topic=52151.0)
I created a patched plugin for myself. The patched scripts calls the powerdown script using the full path.
You can find my version here:
`plg` file for installing: https://raw.github.com/rgls/dynamix/master/unRAIDv6/dynamix.s3.sleep.plg
the actual patch to the s3_sleep script: https://github.com/rgls/dynamix/commit/ebf1066771d757df6fa62ba85e13c5abb560db97

A pull request doesn't really make sense here, since you'll have to recreate the txz file.

**Comment by bergware** [comment]
Thanks for reporting. I have made a correction in the script, and new version is available as update thru plugin manager.
