### ISSUE TITLE
Dynamix System Statistics 2023.02.12a

### ISSUE THREAD

**Issue by napgiver** [bergware/dynamix#71]
Not sure who to report this to, so I'll start here. Nothing happens after clicking the _UPDATE_ button.

![Dynamix System Statistics 2023 02 12a](https://user-images.githubusercontent.com/42033803/218341670-7fb4b107-e868-42a3-a937-ecea2706e555.png)

**Comment by bergware** [comment]
Check for update and install version 2023.02.13

**Comment by napgiver** [comment]
That worked. Thanks 👍
