### ISSUE TITLE
autofan, no longer loads

### ISSUE THREAD

**Issue by C4Wiz** [bergware/dynamix#8]
noticed the other day that the autofan page is mostly missing. cannot start or configure or anything at all. this is not a new install. i have been using this plugin since the begining.

im on 6.3.0 RC5

![screen shot 2016-12-01 at 3 37 06 pm](https://cloud.githubusercontent.com/assets/3883521/20815682/15e484fa-b7dc-11e6-87d4-a44f73484c98.png)

**Comment by bergware** [comment]
This is caused by incompatiblity with PHP7. A new version of autofan is released and corrects this.
